# For Atom Feed
author: Index Exchange
email: martin.laws@indexexchange.com
title: Hack Index

# standard jekyll configuration
url: http://indexexchange.github.io
baseurl: /hackathon

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

include:
- _assets

sass:
  sass_dir: _assets/stylesheets/

# Custom site configuration
lang: en

gems:
  - octopress-autoprefixer
