# For Atom Feed
author: Index Exchange
email: martin.laws@indexexchange.com
title: Hack Index

# standard jekyll configuration

baseurl: /hackathon
# parentsite: https://services.github.com
# permalink: /articles/:title
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

include:
- _assets
# - _javascript
sass:
  sass_dir: _assets/stylesheets/

# Custom site configuration
lang: en

gems:
  - octopress-autoprefixer
